config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "static_pages#home"
  resources :groups do 
    resources :budget_transactions
  end
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, author_id: user.id
    can :manage, BudgetTransaction, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget_transaction.rb
class BudgetTransaction < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_transactions, dependent: :destroy
  has_many :groups, through: :group_transactions

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_transactions, dependent: :destroy
  has_many :budget_transactions, through: :group_transactions

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/group_transaction.rb
class GroupTransaction < ApplicationRecord
  belongs_to :group
  belongs_to :budget_transaction
  after_destroy :destroy_orphaned_budget_transaction

  def destroy_orphaned_budget_transaction
    budget_transaction.destroy if budget_transaction.group_transactions.empty?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :budget_transactions, foreign_key: :author_id, dependent: :destroy
  has_many :groups, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?
  helper_method :header_title

  def header_title
    @header_title || nil
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.permit(:sign_in) do |u|
      u.permit(:email, :password, :remember_me)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/budget_transactions_controller.rb
class BudgetTransactionsController < ApplicationController
  def show
    @budget_transaction = BudgetTransaction.find_by_id(params[:id])
    @group = Group.find_by_id(params[:group_id])
    if @budget_transaction.nil?
      redirect_to group_path(@group)
    else
      @header_title = 'Transaction'
    end
  end

  def new
    @group = Group.find_by_id(params[:group_id])
    @groups = Group.where(author: current_user)
    @budget_transaction = BudgetTransaction.new
    @header_title = 'New Transaction'
  end

  def create
    @group = params[:group_id]
    @groups = params[:group_ids]
    @budget_transaction = current_user.budget_transactions.build(budget_transaction_params)
    if @budget_transaction.save
      GroupTransaction.create(budget_transaction: @budget_transaction, group_id: @group)
      unless @groups.nil? || @groups.empty?
        @groups.each do |group_id|
          GroupTransaction.create(budget_transaction: @budget_transaction, group_id:)
        end
      end
      redirect_to group_path(@group)
      flash[:notice] = 'Transaction was successfully created.'
    else
      flash[:error] = @budget_transaction.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    @budget_transaction = BudgetTransaction.find_by_id(params[:id])
    group_id = params[:group_id]
    if @budget_transaction.destroy
      redirect_to group_path(group_id), notice: 'Transaction deleted'
    else
      flash[:error] = @budget_transaction.errors.full_messages.to_sentence
    end
  end

  private

  def budget_transaction_params
    params.require(:budget_transaction).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.joins('LEFT JOIN group_transactions ON groups.id = group_transactions.group_id')
      .joins('LEFT JOIN budget_transactions ON group_transactions.budget_transaction_id = budget_transactions.id')
      .where(author_id: current_user.id)
      .select('groups.*, SUM(budget_transactions.amount) as total_amount')
      .group('groups.id')
    @header_title = 'Categories'
  end

  def show
    if Group.find_by_id(params[:id]).nil?
      redirect_to groups_path
    else
      @group = Group.includes(group_transactions: :budget_transaction).find_by_id(params[:id])
      @header_title = 'Category'
    end
  end

  def new
    @group = Group.new
    @header_title = 'New Category'
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = 'Category created Successfully'
      redirect_to groups_path
    else
      flash[:error] = @group.errors.full_messages.to_sentence
      redirect_to new_group_path
    end
  end

  def destroy
    @group = Group.find_by_id(params[:id])
    if @group.destroy
      flash[:notice] = 'Category deleted'
      redirect_to groups_path
    else
      flash[:error] = @group.errors.full_messages.to_sentence
      redirect_to request.referrer
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon).merge(author: current_user)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :check_user
  def home; end

  private

  def check_user
    return unless user_signed_in?

    redirect_to groups_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budget_transactions_helper.rb
module BudgetTransactionsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/budget_transactions/new.html.erb
<section class="p-2">
  <%= form_with(model: [ @group, @budget_transaction ], url: group_budget_transactions_path(@group), local: true) do |f|%>
    <div class="flex flex-col gap-3" >
      <div>
        <%= f.text_field :name, autofocus: true, placeholder: "Transaction name", class:"w-full border-b border-0 ring-0 border-slate-300 focus:border-gray-600 focus:border-b-2"%>
      </div>
      <div>
        <%= f.number_field :amount, min: 0, autofocus: true, placeholder: "Amount", class:"w-full border-b border-0 ring-0 border-slate-300 focus:border-gray-600 focus:border-b-2"%>
      </div>
      <%unless @groups.length < 2%>
        <p class="text-green-500 font-semibold">Add to your other categories</p>
        <% @groups.each do |group| %>
          <% unless group.id == @group.id %>
            <div>
              <%= check_box_tag 'group_ids[]', group.id %>
              <%= label_tag "group_ids_#{group.id}", group.name %>
            </div>
          <% end %>
        <% end %>
      <%end%>
      <div>
        <%= f.submit "Create", class:"w-full px-3 py-2.5 text-md font-medium text-white bg-second-color focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg text-center"%>
      </div>
    </div>
  <%end%>
</section>

app/views/budget_transactions/show.html.erb
<section class="p-2 bg-slate-100 min-h-full flex flex-col">
  <article class="bg-white p-2 flex flex-col gap-2">
    <div class="flex gap-2 items-center border-b py-2">
      <%= image_tag(@group.icon)%>
      <p><%= @group.name%></p>
    </div>
    <div class="flex gap-2 flex-col border-b py-2">
      <p>Transaction: <%= @budget_transaction.name %></p>
      <span class="text-xs text-text-color"><%= @budget_transaction.created_at.strftime("%d %B %Y")%> At <%= @budget_transaction.created_at.in_time_zone.strftime("%I:%M %p") %></span>
    </div>
    <div class="flex justify-between items-center py-2">
      <p>TOTAL PAYMENT</p>
      <span>$<%= @budget_transaction.amount %></span>
    </div>
  </article>
  <div class="bg-red-600 p-2 mt-auto">
    <%= button_to "Delete Transaction", group_budget_transaction_path(@group, @budget_transaction), method: :delete, class: "inline-block w-full px-5 py-3 text-base font-medium text-center text-white focus:outline-none border border-white"%>
  </div>
</section>

app/views/groups/index.html.erb
<section class="bg-slate-100 flex flex-col min-h-full">
  <div class="text-center bg-white shadow-md text-text-color">
    <span>
      Total Spendings $<%= @groups.sum { |group| group.total_amount || 0 }%>
    </span>
  </div>
  <%if @groups.empty?%>
    <h1>No categories yet. Make a new category</h1>
  <%else%>
    <ul class="p-3 flex flex-col gap-3">
      <% @groups.each do |group|%>
        <%= link_to group_path(group) do %>
          <li class="flex items-center gap-2 border p-2 bg-white">
            <%= image_tag group.icon%>
            <div class="flex justify-between w-full">
              <div>
                <p><%= group.name%></p>
                <span class="text-xs text-text-color"><%= group.created_at.strftime("%d %B %Y")%></span>
              </div>
              <div>
                <span>$<%= group.total_amount || 0%></span>
              </div>
            </div>
          </li>
        <%end%>
      <%end%>
    </ul>
  <%end%>
  <div class="mt-auto p-2 bg-second-color">
    <%= link_to "Add new category", new_group_path, class: "inline-block w-full px-5 py-3 text-base font-medium text-center text-white focus:outline-none border border-white"%>
  </div>
</section>

app/views/groups/new.html.erb
<section class="p-2">
  <%= form_with(model: @group, local: true) do |f|%>
    <div class="flex flex-col gap-3" >
      <div>
        <%= f.text_field :name, autofocus: true, autocomplete: "category name", placeholder: "category name", class:"w-full border-b border-0 ring-0 border-slate-300 focus:border-gray-600 focus:border-b-2"%>
      </div>
      <div class="flex gap-3 flex-col">
        <p>Choose an Icon:</p>
        <div class="flex items-center gap-3">
          <%= f.radio_button :icon, "https://img.icons8.com/doodle/48/stack-of-money.png", id: "bills" %>
          <%= label :icon, for: "bills" do %>
            <%= image_tag("https://img.icons8.com/doodle/48/stack-of-money.png") %>
          <% end %>
        </div>
        <div class="flex items-center gap-3">
          <%= f.radio_button :icon, "https://img.icons8.com/color/48/funimation.png", id: "entertainment" %>
          <%= label :icon, for: "entertainment" do %>
            <%= image_tag("https://img.icons8.com/color/48/funimation.png") %>
          <% end %>
        </div>
        <div class="flex items-center gap-3">
          <%= f.radio_button :icon, "https://img.icons8.com/color/48/money-box--v1.png", id: "savings" %>
          <%= label :icon, for: "savings" do %>
            <%= image_tag("https://img.icons8.com/color/48/money-box--v1.png") %>
          <% end %>
        </div>
        <div class="flex items-center gap-3">
          <%= f.radio_button :icon, "https://img.icons8.com/fluency/48/hamburger.png", id: "food" %>
          <%= label :icon, for: "food" do %>
            <%= image_tag("https://img.icons8.com/fluency/48/hamburger.png") %>
          <% end %>
        </div>
        <div class="flex items-center gap-3">
          <%= f.radio_button :icon, "https://img.icons8.com/fluency/48/car--v1.png", id: "car" %>
          <%= label :icon, for: "car" do %>
            <%= image_tag("https://img.icons8.com/fluency/48/car--v1.png") %>
          <% end %>
        </div>
      </div>
      <div>
        <%= f.submit "Save", class:"w-full px-3 py-2.5 text-md font-medium text-white bg-second-color focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg text-center"%>
      </div>
    </div>
  <%end%>
</section>

app/views/groups/show.html.erb
<section class="border min-h-full bg-slate-100 flex flex-col">
  <div class="text-center bg-white shadow-md text-text-color">
    <span>
      <% if @group.group_transactions.empty? %>
        Total spendings $0
      <%else%>
        Total spendings $<%= @group.group_transactions.sum { |gt| gt.budget_transaction.amount } %>
      <%end%>
    </span>
  </div>
  <ul class="p-3 flex flex-col gap-3">
    <% if @group.group_transactions.empty? %>
      <h1>No transactions yet<h1>
    <%else%>
      <% @group.group_transactions.each do |group_transaction| %>
        <%= link_to group_budget_transaction_path(@group, group_transaction.budget_transaction) do%>
          <li class="flex items-center justify-between border p-2 bg-white">
            <div>
              <p><%= group_transaction.budget_transaction.name%></p>
              <span class="text-xs text-text-colo"><%= group_transaction.created_at.strftime("%d %B %Y") %></span>
            </div>
            <div>
              <span>$<%= group_transaction.budget_transaction.amount%></span>
            </div>
          </li>
        <%end%>
      <%end%>
    <%end%>
  </ul>
  <div class="mt-auto">
    <div class="bg-second-color p-2">
      <%= link_to "Add Transaction", new_group_budget_transaction_path(@group), class: "inline-block w-full px-5 py-3 text-base font-medium text-center text-white focus:outline-none border border-white"%>
    </div>
    <div class="bg-red-600 p-2">
      <%= button_to "Delete Category", group_path(@group), method: :delete, class: "inline-block w-full px-5 py-3 text-base font-medium text-center text-white focus:outline-none border border-white"%>
    </div>
  </div>
</section>

app/views/layouts/_header.html.erb
<header class="bg-main-color border-gray-200 py-2 md:py-0 md:px-4">
  <nav class="max-w-screen-xl flex flex-wrap items-center justify-between md:gap-5 md:justify-between mx-auto md:p-4">
    <button data-controller="menu" data-action="click->menu#historyBack" type="button">
      <%= image_tag("https://img.icons8.com/ios-filled/50/FFFFFF/back.png", size: "30x30")%>
    </button>
    <% if header_title%>
      <span class="text-white"><%= header_title%></span>
    <%end%>
    <div class="flex justify-between md:hidden">
      <button data-controller="menu"  data-menu-toggle="navbar-search" data-action="click->menu#toggleHidden" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm" aria-controls="navbar-search" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
          </svg>
      </button>
    </div>
    <div class="items-center hidden w-full relative justify-between w-full md:flex md:w-auto md:order-1" id="navbar-search">
      <ul class="absolute md:static bg-main-color w-full flex flex-col md:items-center p-4 md:p-0 font-medium md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0">
        <% if user_signed_in?%>
          <li class="border-b md:border-b-0 px-0">
              <%= button_to "logout", destroy_user_session_path, method: :delete, class: "block py-2 px-0 text-slate-200  md:hover:text-white"%>
          </li>
        <%else%>
          <li class="border-b md:border-b-0 px-0">
              <%= link_to "login", new_user_session_path, class: "block py-2 px-0 text-slate-200 md:hover:text-white md:p-0"%>
          </li>
          <li class="border-b md:border-b-0 px-0">
              <%= link_to "Sign Up", new_user_registration_path, class: "block py-2 px-0 text-slate-200 md:hover:text-white"%>
          </li>
        <%end%>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="flex flex-col h-screen">
      <%= render "layouts/header", header_title: header_title%>
      <main class="md:container md:p-4 flex-grow">
        <% flash.each do |message_type, message| %>
          <div class="bg-sky-400 text-white w-auto rounded-lg p-2 border border-sky-700 shadow-inner shadow-lg" role="alert">
            <%= message %>
          </div>
        <% end %>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<section class="flex flex-col min-h-full bg-slate-100 items-center">
  <div class="my-auto flex flex-col justify-center">
    <p class="text-4xl font-black text-gray-900 font-mono">Budget Buddy</p>
  </div>
  <div class="flex flex-col w-full mt-auto justify-self-end">
    <%= link_to "Login", new_user_session_path, class: "w-full p-3 text-center font-semibold bg-main-color text-white" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "w-full p-3 text-center font-semibold bg-slate-200 text-text-color" %>
  </div>
</section>